-- 20260704000000_init_schema.sql
-- Migration to set up the Aviator crash multiplier data logging table.

-- Create table to log Aviator crash events
CREATE TABLE IF NOT EXISTS public.crash_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    multiplier NUMERIC(8, 2) NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Comments on table columns
COMMENT ON TABLE public.crash_history IS 'Stores historical crash multiplier logs for time-series modeling';
COMMENT ON COLUMN public.crash_history.multiplier IS 'The multiplier at which the airplane flew away';
COMMENT ON COLUMN public.crash_history.timestamp IS 'The exact UTC time when the round completed';

-- Create descending index on timestamp to allow fast indexing of recent multiplier sequences
CREATE INDEX IF NOT EXISTS idx_crash_history_timestamp ON public.crash_history (timestamp DESC);
