-- Create multiplier history log table
CREATE TABLE IF NOT EXISTS multiplier_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    multiplier NUMERIC(10, 2) NOT NULL
);

-- Index by timestamp descending to support low-latency time-series queries
CREATE INDEX IF NOT EXISTS idx_multiplier_history_timestamp ON multiplier_history (timestamp DESC);

-- Create signals logs table for backtesting analytics
CREATE TABLE IF NOT EXISTS pattern_signals (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    trigger_type VARCHAR(50) NOT NULL,
    win_probability NUMERIC(5, 4) NOT NULL,
    recommended_cashout NUMERIC(5, 2) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_pattern_signals_created_at ON pattern_signals (created_at DESC);
